import numpy as np
import pandas as pd

pd.set_option('display.max_rows', 120)
df = pd.read_csv('/Users/ismailmustafa/Downloads/Motor_Vehicle_Collisions_-_Crashes.csv')

df['Year of Accident'] = df['CRASH DATE'].str[-4:]

df['Month of Accident'] = df['CRASH DATE'].str[0:2]
df['Month of Accident'] = df['Month of Accident'].replace("01", "January ")
df['Month of Accident'] = df['Month of Accident'].replace("02", "February ")
df['Month of Accident'] = df['Month of Accident'].replace("03", "March ")
df['Month of Accident'] = df['Month of Accident'].replace("04", "April ")
df['Month of Accident'] = df['Month of Accident'].replace("05", "May ")
df['Month of Accident'] = df['Month of Accident'].replace("06", "June ")
df['Month of Accident'] = df['Month of Accident'].replace("07", "July ")
df['Month of Accident'] = df['Month of Accident'].replace("08", "August ")
df['Month of Accident'] = df['Month of Accident'].replace("09", "September ")
df['Month of Accident'] = df['Month of Accident'].replace("10", "October ")
df['Month of Accident'] = df['Month of Accident'].replace("11", "November ")
df['Month of Accident'] = df['Month of Accident'].replace("12", "December ")


df['Month & Year of Accident'] = df['Month of Accident'] + df['Year of Accident']

from pandas import factorize

labels, categories = factorize(df["BOROUGH"])
df["CRASH DATE"] = labels
print(abs(df["NUMBER OF PERSONS INJURED"].corr(df["CRASH DATE"])))

#print(df['CONTRIBUTING FACTOR VEHICLE 1'].unique())

#print (df.columns)
#print (df.corr().columns)

"""
print(sum((df['Year of Accident'] == '2021')))
print(sum((df['Year of Accident'] == '2020')))
print(sum((df['Year of Accident'] == '2019')))
print(sum((df['Year of Accident'] == '2018')))
print(sum((df['Year of Accident'] == '2017')))
print(sum((df['Year of Accident'] == '2016')))
print(sum((df['Year of Accident'] == '2015')))
print(sum((df['Year of Accident'] == '2014')))
print(sum((df['Year of Accident'] == '2013')))
print(sum((df['Year of Accident'] == '2012')))
"""

"""
print("Following Too Closely")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Following Too Closely') & (df['Year of Accident'] == '2012')))

print("Pavement Slippery")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Slippery') & (df['Year of Accident'] == '2012')))

print("Unspecified")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unspecified') & (df['Year of Accident'] == '2012')))

print("Driver Inattention/Distraction")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inattention/Distraction') & (df['Year of Accident'] == '2012')))

print("Other Vehicular")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Vehicular') & (df['Year of Accident'] == '2012')))

print("Passing Too Closely")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing Too Closely') & (df['Year of Accident'] == '2012')))

print("Passing or Lane Usage Improper")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passing or Lane Usage Improper') & (df['Year of Accident'] == '2012')))

print("Driver Inexperience")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driver Inexperience') & (df['Year of Accident'] == '2012')))

print("Failure to Yield Right-of-Way")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Yield Right-of-Way') & (df['Year of Accident'] == '2012')))

print("Brakes Defective")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Brakes Defective') & (df['Year of Accident'] == '2012')))

print("Turning Improperly")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Turning Improperly') & (df['Year of Accident'] == '2012')))

print("Unsafe Speed")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Speed') & (df['Year of Accident'] == '2012')))

print("Backing Unsafely")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Backing Unsafely') & (df['Year of Accident'] == '2012')))

print("Reaction to Uninvolved Vehicle")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Reaction to Uninvolved Vehicle') & (df['Year of Accident'] == '2012')))

print("View Obstructed/Limited")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'View Obstructed/Limited') & (df['Year of Accident'] == '2012')))

print("Steering Failure")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Steering Failure') & (df['Year of Accident'] == '2012')))

print("Traffic Control Disregarded")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Disregarded') & (df['Year of Accident'] == '2012')))

print("Drugs (illegal)")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Drugs (illegal)') & (df['Year of Accident'] == '2012')))

print("Aggressive Driving/Road Rage")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Aggressive Driving/Road Rage') & (df['Year of Accident'] == '2012')))

print("Fell Asleep")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fell Asleep') & (df['Year of Accident'] == '2012')))

print("Pedestrian/Bicyclist/Other Pedestrian Error/Confusion")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion') & (df['Year of Accident'] == '2012')))

print("Alcohol Involvement")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Alcohol Involvement') & (df['Year of Accident'] == '2012')))

print("Unsafe Lane Changing")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Unsafe Lane Changing') & (df['Year of Accident'] == '2012')))

print("Pavement Defective")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Pavement Defective') & (df['Year of Accident'] == '2012')))

print("Other Lighting Defects")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Lighting Defects') & (df['Year of Accident'] == '2012')))

print("Oversized Vehicle")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Oversized Vehicle') & (df['Year of Accident'] == '2012')))

print("Animals Action")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Animals Action') & (df['Year of Accident'] == '2012')))

print("Accelerator Defective")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Accelerator Defective') & (df['Year of Accident'] == '2012')))

print("Outside Car Distraction")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Outside Car Distraction') & (df['Year of Accident'] == '2012')))

print("Illnes")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Illnes') & (df['Year of Accident'] == '2012')))

print("Glare")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Glare') & (df['Year of Accident'] == '2012')))

print("Driverless/Runaway Vehicle")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Driverless/Runaway Vehicle') & (df['Year of Accident'] == '2012')))

print("Passenger Distraction")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Passenger Distraction') & (df['Year of Accident'] == '2012')))

print("Tire Failure/Inadequate")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tire Failure/Inadequate') & (df['Year of Accident'] == '2012')))

print("Lost Consciousness")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lost Consciousness') & (df['Year of Accident'] == '2012')))

print("Obstruction/Debris")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Obstruction/Debris') & (df['Year of Accident'] == '2012')))

print("Failure to Keep Right")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Failure to Keep Right') & (df['Year of Accident'] == '2012')))

print("Eating or Drinking")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Eating or Drinking') & (df['Year of Accident'] == '2012')))

print("Cell Phone (hands-free)")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hands-free)') & (df['Year of Accident'] == '2012')))

print("Cell Phone (hand-Held)")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Cell Phone (hand-Held)') & (df['Year of Accident'] == '2012')))

print("Lane Marking Improper/Inadequate")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Lane Marking Improper/Inadequate') & (df['Year of Accident'] == '2012')))

print("Using On Board Navigation Device")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Using On Board Navigation Device') & (df['Year of Accident'] == '2012')))

print("Headlights Defective")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Headlights Defective') & (df['Year of Accident'] == '2012')))

print("Fatigued/Drowsy")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Fatigued/Drowsy') & (df['Year of Accident'] == '2012')))

print("Tow Hitch Defective")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tow Hitch Defective') & (df['Year of Accident'] == '2012')))

print("Tinted Windows")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Tinted Windows') & (df['Year of Accident'] == '2012')))

print("Physical Disability")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Physical Disability') & (df['Year of Accident'] == '2012')))

print("Vehicle Vandalism")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Vehicle Vandalism') & (df['Year of Accident'] == '2012')))

print("Prescription Medication")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Prescription Medication') & (df['Year of Accident'] == '2012')))

print("Texting")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Texting') & (df['Year of Accident'] == '2012')))

print("Traffic Control Device Improper/Non-Working")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Traffic Control Device Improper/Non-Working') & (df['Year of Accident'] == '2012')))

print("Listening/Using Headphones")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Listening/Using Headphones') & (df['Year of Accident'] == '2012')))

print("Other Electronic Device")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Other Electronic Device') & (df['Year of Accident'] == '2012')))

print("Windshield Inadequate")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Windshield Inadequate') & (df['Year of Accident'] == '2012')))

print("Shoulders Defective/Improper")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == 'Shoulders Defective/Improper') & (df['Year of Accident'] == '2012')))

print("Blank")
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2021')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2020')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2019')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2018')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2017')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2016')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2015')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2014')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2013')))
print(sum((df['CONTRIBUTING FACTOR VEHICLE 1'] == '') & (df['Year of Accident'] == '2012')))
#print(df['Month & Year of Accident'].value_counts()) --> Accidents per month
"""
